export {LoginComponent} from './LoginComponent'
export {PostsComponent} from './PostsComponent'
export {FriendsComponent} from './FriendsComponent'
export {UsersComponent} from './UsersComponent'
export {DialogsComponent} from './DialogsComponent'