export {LoginComponent} from './LoginComponent'
export {PostsComponent} from './PostsComponent'
export {FriendsComponent} from './FriendsComponent'
export {SearchComponent} from './SearchComponent'
export {ProfileComponent} from './ProfileComponent'
export {DialogsComponent} from './DialogsComponent'
export {CurrentDialogComponent} from './CurrentDialogComponent'