version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres:15.4-alpine3.18
    environment:
      POSTGRES_DB: "otusdb"
      POSTGRES_USER: "sa"
      POSTGRES_PASSWORD: "medtex"
      POSTGRESQL_REPLICATION_MODE: "master"
      POSTGRESQL_REPLICATION_USER: "repl_user"
      POSTGRESQL_REPLICATION_PASSWORD: "repl_password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ../migrations:/docker-entrypoint-initdb.d
      - otusdb-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  profile_go:
    container_name: profile_go
    image: profile_go:$APP_VERSION
    build:
      context: ..
      dockerfile: docker/go/profile.Dockerfile
      target: final
      args:
        APP_VERSION: $APP_VERSION
    environment:
      - EXPOSE_PORT=$EXPOSE_PORT
      - POSTGRESQL_CONNECTION=$POSTGRESQL_CONNECTION	
    ports:
      - "8001:80"
    depends_on:
      - postgres

  profile_cs:
    container_name: profile_cs
    image: profile_cs:$APP_VERSION
    build:
      context: ..
      dockerfile: docker/cs/profile.Dockerfile
      target: final
      args:
        APP_VERSION: $APP_VERSION
    environment:
      - EXPOSE_PORT=$EXPOSE_PORT
      - POSTGRESQL_CONNECTION=$POSTGRESQL_CONNECTION_CS	
    ports:
      - "8002:80"
    depends_on:
      - postgres

  pgbouncer:
    image: edoburu/pgbouncer
    restart: always
    user: postgres
    depends_on:
      - postgres
    ports:
      - "6432:6432"
    environment:
      POSTGRESQL_HOST: postgres
      POSTGRESQL_PORT: 5432
      POSTGRESQL_DATABASE: otusdb
      POSTGRESQL_USERNAME: sa
      POSTGRESQL_PASSWORD: medtex
      AUTH_TYPE: md5
      AUTH_FILE: /etc/pgbouncer/userlist.txt
    volumes:
      - ./config/pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
      - ./config/pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt

volumes:
  otusdb-data: